#!/bin/sh

# The MIT License (MIT)
# 
# Copyright (c) 2018-2019 Yury Gribov
# 
# Use of this source code is governed by The MIT License (MIT)
# that can be found in the LICENSE.txt file.

# Reads binary APIs from a list of shlibs.
# TODO: implement this in a saner way

set -eu

print_help_and_exit() {
  cat <<EOF
Usage: $(basename $0) [OPT]... FILE...
Prints symbols exported from FILE.

Options:
  -x              Enable shell tracing (for debug).
  -h, --help      Print this help and exit.
  -v, --verbose   Print diagnostic info (can use more than once for more details).
  --permissive    Ignore dummy symbols introduced by ld (_edata, __bss_start, etc.)
                  and libgcc (_init, _fini).
  -e, --export    List exported symbols (default).
  -i, --import    List imported symbols.
EOF
  exit 1

}

ARGS=$(getopt -o 'hkiexv' --long 'help,verbose,import,export,permissive' -n $(basename $0) -- "$@")
eval set -- "$ARGS"

V=0
PERM=
EXPORT=1
while true; do
  case "$1" in
    -x)
      set -x
      shift
      ;;
    -h | --help)
      print_help_and_exit
      ;;
    -v | --verbose)
      V=$((V + 1))
      shift
      ;;
    -i | --import)
      EXPORT=
      shift
      ;;
    -e | --export)
      EXPORT=1
      shift
      ;;
    --permissive)
      PERM=1
      shift
      ;;
    --)
      shift
      break
      ;;
    -*)
      error "unknown option: $1"
      ;;
    *)
      error 'internal error'
      ;;
  esac
done

if [ $# -eq 0 ]; then
  print_help_and_exit
fi

# (if test -n "$EXPORT"; then grep -v '@'; else sed 's/@.*//'; fi) \
for l in "$@"; do
  readelf -W --dyn-syms $l \
    | grep '^ *[0-9]\+:' \
    | grep -v '\<ABS\>' \
    | (if test -n "$EXPORT"; then grep -v '\<UND\>'; else grep '\<UND\>'; fi) \
    | awk 'BEGIN {FS="[ \t]+"} {print $9}' \
    | sed 's/@@.*//' \
    | sed 's/@.*//' \
    | grep -v '^$' \
    | (if test -z "$PERM"; then cat; else grep -v '^\(__bss_start\|_edata\|_init\|_fini\|_etext\|__etext\|_end\)$'; fi) \
    | sort -u
done | sort -u
